export const APP_CONFIG = {
  APP_NAME: 'HackLingo',
  APP_VERSION: '1.0.0',
  BUILD_NUMBER: 1,
  MIN_LESSON_TIME_SECONDS: 30,
  MAX_SESSION_CHALLENGES: 20,
  HEARTS_REFILL_HOURS: 4,
  STREAK_FREEZE_DURATION_HOURS: 24,
  CHALLENGE_TIME_LIMIT_SECONDS: 60,
  MAX_HINT_REVEALS: 3,
  LEADERBOARD_PAGE_SIZE: 20,
  FRIEND_LIMIT: 50,
} as const;

export const API_CONFIG = {
  BASE_URL: 'https://api.hacklingo.app',
  TIMEOUT_MS: 10_000,
  RETRY_COUNT: 2,
  CACHE_TTL_SECONDS: 300,
} as const;
